# Generated by Django 4.1.2 on 2022-11-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="zip",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
